### ISSUE TITLE
Sauce code

### ISSUE THREAD

**Issue by lhypl** [aweijnitz/recipe-el_fuego_viviente#5] opened 2018-07-19 01:56 UTC
Where is the sauce code? I could compile the chilli sauce right? The instructions didn't provide any ingredients :rainbow:

**Comment by aweijnitz** [comment] 2018-07-20 05:13
For this repo, we must understand transitive verb _to compile_ in it's non-technical [meaning](https://www.merriam-webster.com/dictionary/compile). In short it is a composition of gathered materials, to form a sauce. 

**Resolution:** Close Won't Fix. Works as intended. :-)

**Closed by aweijnitz** 2018-07-20 05:13 UTC
